### ISSUE TITLE
Allow static usage

### ISSUE THREAD

**Issue by Klaim** [Arokha/ep2-helper#8]
Currently cloning the repo and launching the index.html will fail (with various errors).

Suggestion: Setup this project to be able to have a local copy of it running on a laptop.

Alternative suggestion: set it up so that it's easy to run in a LAMP system, so that it can be used in a local network or locally. If it's already possible, add documentation (in the Readme?) to explain what need to be done to achieve that.

**Comment by Arokha** [comment]
It would work fine in static usage, the issue is actually that browsers don't allow file:// URIs to access other file:// URIs on your computer for security reasons.

It works fine locally if you start chrome with `chrome.exe --allow-file-access-from-files`, and Firefox has a similar workaround in `about.config`.

Alternatively you can copy all the JS and CSS and everything into a single file. So, it's not really in the site design so much as in browsers deciding this is the way to go for security reasons. It's not something you can work around unless you combine the entire thing into a single file.

See here: https://stackoverflow.com/questions/16487803/why-does-this-filesystem-api-requestquota-call-fail

https://stackoverflow.com/questions/18586921/how-to-launch-html-using-chrome-at-allow-file-access-from-files-mode#33801287

Those also contain guides for installing a local webserver because the above option is slightly dangerous.
